select * from shopping limit 40;

--Q1.What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from shopping
group by gender

--Q2.Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from shopping
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from shopping)
limit 20;

--Q3.Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from shopping
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4.Compare the average Purchase Amounts between Standard and Express Shipping?
select shipping_type,ROUND(AVG(purchase_amount),2) as "Average Purchase Amount"
from shopping
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue? 
select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from shopping
group by subscription_status
order by avg_spend,total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from shopping
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as(
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ElSE 'Loyal'
	END as customer_segment
from shopping
)
select customer_segment,COUNT(*) as "Number of customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM shopping
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from shopping
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as total_revenue
from shopping
group by age_group
order by total_revenue desc;